openstax-poland/cnx-designer

src/cnxml/deserialize.js

https://trello.com/c/DuU7c9pw/322-text-inside-list-items-is-ommited

Handle all types of content inside <item> tag

---

package.json
src/cnxml/deserialize.js
src/cnxml/index.js
src/cnxml/serialize.js
src/cnxml/xml.js
test/cnxml/de/admonition.js
test/cnxml/de/block-in-para.js
test/cnxml/de/exercise.js
test/cnxml/de/figure-subfigures.js
test/cnxml/de/figure.js
test/cnxml/de/inline.js
test/cnxml/de/invalid-child.js
test/cnxml/de/list.js
test/cnxml/index.js
test/cnxml/se/admonition.js
test/cnxml/se/exercise.js
test/cnxml/se/figure-subfigures.js
test/cnxml/se/figure.js
test/cnxml/se/inline.js
test/cnxml/se/list.js
test/cnxml/se/section.js
test/index.js
test/plugins/index.js
test/util/cnxml.js
test/util/compareHtml.js
test/util/dropKeys.js
test/util/h.js

Add tests for, and fix, CNXML de/serialization

---

src/cnxml/deserialize.js
src/cnxml/serialize.js
src/plugins/admonition/schema.js
src/plugins/exercise/schema.js
src/plugins/figure/schema.js
src/plugins/section/schema.js

What elements should support classes?
From one perspective we could handle all elements, but in another we probably will never use class on paragraphs or list items.
https://github.com/katalysteducation/adaptarr-front/pull/20

Handle classes

---

src/plugins/xref/render.js
src/plugins/xref/schema.js

https://github.com/katalysteducation/adaptarr-front/pull/31

Render links and add proper data validation

---

src/cnxml/deserialize.js
src/cnxml/serialize.js
src/plugins/code/handlers.js
src/plugins/code/index.js
src/plugins/code/render.js
src/plugins/code/schema.js
src/plugins/index.js
src/plugins/section/schema.js
src/plugins/text/render.js
src/plugins/text/schema.js
test/index.js
test/plugins/code/handle-backspace-inline.js
test/plugins/code/handle-backspace-lines.js
test/plugins/code/handle-backspace.js
test/plugins/code/handle-enter-inline.js
test/plugins/code/handle-enter.js
test/plugins/code/handle-shift-enter.js
test/plugins/code/insert-nested.js
test/plugins/code/insert.js
test/plugins/code/query-active.js
test/plugins/code/wrap-with-code.js
test/util/dropKeys.js
test/util/h.js
test/util/plugins.js

UI: https://github.com/katalysteducation/adaptarr-front/pull/25

Support for inline and block <code> tags

---

src/cnxml/serialize.js
test/cnxml/de/code.js
test/cnxml/se/code.js

Add serialize function for text and use it for code elements
Add tests for code and set id to code blocks when serializing elements

Small fixes

---

src/plugins/admonition/schema.js
test/plugins/admonition/handle-enter-title.js
test/plugins/admonition/schema-two-titles.js

When someone press enter inside title, second part will become paragraph.

Fix enter handling inside note title

---

src/plugins/figure/schema.js
test/plugins/figure/handle-enter-in-caption.js

Handle enter inside figure_caption

Handle enter inside figure_caption

---

src/plugins/code/index.js
src/plugins/code/schema.js
src/plugins/index.js
src/plugins/term/index.js
src/plugins/term/schema.js

It's needed for suggestions: https://github.com/katalysteducation/adaptarr-front/pull/48

Allow setting types for allowed inlines in Document

---

src/plugins/figure/render.js

Since dragging figures is causing weird things it's easier to just disable this option.
https://trello.com/c/iHmQ6u5K/310-disable-dragging-or-fix-figure-dragging

Do not allow dragging figures

---

src/persistence/index.js

Working version of UI which is based on those changes: https://github.com/openstax-poland/adaptarr-front/pull/110

Add toJS() and replaceDatabase() to PersistDB

---

src/cnxml/index.js

https://github.com/openstax-poland/adaptarr-front/pull/108

Preserve title and language

---

src/plugins/xref/schema.js

https://github.com/openstax-poland/adaptarr-front/pull/166

Remove empty docrefs

---

src/cnxml/document.js
src/plugins/code/schema.js
test/cnxml/de/code.js
test/cnxml/se/code.js
test/plugins/code/change-language.js

Allow setting lang attribute on code blocks and inlines.
https://github.com/openstax-poland/adaptarr-front/issues/171
https://github.com/openstax-poland/adaptarr-front/pull/172

Allow setting lang attribute on code blocks and inlines

---

src/persistence/index.js

Change Persistence's iterate to take a non-asynchronous closure

---

src/cnxml/document.js
src/plugins/figure/commands.js
src/plugins/media/render.js
src/plugins/media/schema.js
test/cnxml/de/figure.js
test/cnxml/de/whitespace.js
test/cnxml/se/figure-subfigures.js
test/cnxml/se/figure.js
test/plugins/figure/insert-additional-image.js
test/plugins/figure/insert-audio.js
test/plugins/figure/insert-caption.js
test/plugins/figure/insert-video.js
test/util/h.js

Things to consider:
Currently `media` is allowed only inside `figure`.
Should we allow `media` also outside `figure`?
https://github.com/openstax-poland/adaptarr-front/issues/222

Add support for audio and video elements

---

src/cnxml/glossary.js
src/plugins/definition/schema.js
test/cnxml/de/admonition-with-glossary.js
test/cnxml/se/admonition-with-glossary-and-definition.js

https://github.com/openstax-poland/adaptarr-front/issues/290

Add data.reference to definition_term

---

src/cnxml/de.ts
src/cnxml/jsx.ts
src/cnxml/se.tsx
src/interfaces/glossary.ts
test/cnxml/de/inline.js
test/cnxml/se/inline.js

related to https://github.com/openstax-poland/adaptarr-front/issues/401

Support index attribute on terms

---

src/normalize/text.ts
test/behaviours/code/insert-inline.js
test/behaviours/code/insert-line.js
test/behaviours/text/insert-footnote.js
test/handlers/text/backspace-footnote.js
test/handlers/text/backspace-foreign.js
test/handlers/text/backspace-term.js
test/normalization/text/empty-inlines.js

Remove empty inlines without checking a cursor position

---

src/cnxml/de.ts
src/cnxml/index.ts
src/cnxml/jsx.ts
src/cnxml/se.tsx
src/interfaces/classes.ts

- support classes on document and glossary
- fix deserializing classes
- support language on the document
- do not allow empty classes

Support classes on document and handle language

---

package.json
src/cnxml/de.ts
src/cnxml/jsx.ts
src/cnxml/se.tsx
src/interfaces/index.ts
src/interfaces/processingInstruction.ts
test/cnxml/de/processing-instruction.js
test/cnxml/se/processing-instruction.js
test/util/h.js

related to: https://github.com/openstax-poland/adaptarr-front/issues/512 
Fixes #119

Add support for Processing Instruction element

---

src/cnxml/de.ts
src/cnxml/jsx.ts
src/cnxml/se.tsx
src/interfaces/glossary.ts
test/cnxml/de/inline.js
test/cnxml/se/inline.js

related to: https://github.com/openstax-poland/adaptarr-front/issues/515

Term name born died

---

src/normalize/figure.ts
src/normalize/text.ts
src/transforms/figure.ts
test/normalization/figure/alt-text-first-child.js
test/normalization/figure/without-alt-text.js
test/transforms/figure/insert-audio.js
test/transforms/figure/insert-subfigure.js
test/transforms/figure/insert-third-subfigure.js
test/transforms/figure/insert-video.js
test/transforms/figure/insert.js

for: https://github.com/openstax-poland/cnx-designer/issues/116

Add alt text insertnig media

---

src/cnxml/jsx.ts

for: https://github.com/openstax-poland/adaptarr-front/issues/539

Omit reserved attributes when serializing document

---

src/cnxml/de.ts
test/cnxml/de/empty-inlines.js

for: https://app.zenhub.com/workspaces/adaptarr-5d2f43c60f37561a03177ab7/issues/openstax-poland/adaptarr-front/548

Fix deserialization of empty inlines

---

src/cnxml/whitespace.ts
test/cnxml/de/inline.js
test/cnxml/se/inline.js

Fix deserialization of nested inlines ending with white space

---

src/normalize/index.ts
src/normalize/quotation.ts
test/normalization/quotation/invalid-child.js

for: https://github.com/openstax-poland/adaptarr-front/issues/513

Add normalization for quotations

---

src/cnxml/de.ts
src/cnxml/se.tsx
test/cnxml/de/inline.js
test/cnxml/se/inline.js

for: https://github.com/openstax-poland/cnx-designer/issues/131

Add support for emphasis underline

---

src/normalize/figure.ts
test/normalization/figure/in-admonition.js

for: https://github.com/openstax-poland/adaptarr-front/issues/572
It seems that it is already possible to put table into a admonition.

Make admonition a valid parent of figure

---

src/handlers.ts
src/normalize/figure.ts
src/normalize/text.ts
test/normalization/admonition/two-titles.js
test/normalization/figure/title-wrong-order.js
test/normalization/quotation/two-titles.js

https://github.com/openstax-poland/adaptarr-front/issues/639

Allow titles in figures

---

src/normalize/text.ts
test/util/h.js

for: https://github.com/openstax-poland/adaptarr-front/issues/442

Set default language of foreign

---

src/transforms/glossary.ts

for: https://github.com/openstax-poland/adaptarr-backlog/issues/99

Fix finding glossary
